export function reviewPage(){
 const nonce=crypto.randomUUID().replaceAll('-','');
 return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Review tester request — Let’s Build Apps HQ</title><style>
*{box-sizing:border-box}body{margin:0;background:#080c10;color:#f4f7f3;font:17px/1.7 system-ui;padding:7vh 5vw}main{max-width:740px;margin:auto}h1{font-size:clamp(32px,7vw,54px);line-height:1.15;letter-spacing:-.05em}h2{font-size:24px}p,dd{color:#b5c0c7}dt{font-size:13px;text-transform:uppercase;letter-spacing:.12em;color:#d6ff79}dd{margin:4px 0 22px;overflow-wrap:anywhere;white-space:pre-wrap}.card{border:1px solid #35424a;background:#10171c;border-radius:20px;padding:clamp(20px,5vw,38px);margin:24px 0}.status{padding:16px;border-radius:12px;background:#1e3023;color:#d6ff79}button{font:inherit;min-height:48px;padding:12px 22px;border:1px solid #6b7e88;border-radius:10px;background:#15212a;color:#fff;cursor:pointer}button.approve{background:#d6ff79;border-color:#d6ff79;color:#142000}button:focus-visible,a:focus-visible{outline:3px solid #d6ff79;outline-offset:4px}button:disabled{opacity:.5}.actions{display:flex;gap:12px;flex-wrap:wrap}small{color:#99aab4}.error{color:#ffd0b3}a{color:#d6ff79}[hidden]{display:none!important}
</style><main><small>LET’S BUILD APPS HQ · PRIVATE REVIEW</small><h1>Choose who tests next.</h1><p id="status" role="status">Opening the private request…</p><section id="request" class="card" hidden><h2 id="app"></h2><dl><dt>Name</dt><dd id="name"></dd><dt>Invitation email</dt><dd id="email"></dd><dt>Device</dt><dd id="device"></dd><dt>Why they’d like to test</dt><dd id="message"></dd></dl><p id="availability"></p><p id="decision-note">Approving authorizes TestFlight access to this app and future builds in its website tester group. An invitation can be sent only when Apple has approved an external build.</p><div id="actions" class="actions"><button id="approve" class="approve">Approve access</button><button id="decline">Decline</button></div><p><small id="reference"></small></p></section><button id="refresh" hidden>Refresh status</button><p><small>This link is private. Do not forward it. Viewing this page never approves a request.</small></p></main>
<script nonce="${nonce}">
(()=>{const parts=location.hash.slice(1).split('.');history.replaceState(null,'',location.pathname);let id=parts[0],token=parts[1],busy=false;const el=name=>document.getElementById(name);const status=text=>{el('status').textContent=text;};async function load(action){if(busy)return;busy=true;for(const b of document.querySelectorAll('button'))b.disabled=true;try{if(!/^TF-[A-F0-9]{32}$/.test(id||'')||!/^[a-f0-9]{64}$/.test(token||''))throw new Error('Open the complete private review link from your request email.');const response=await fetch(action?'/testflight/decision':'/testflight/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,token,...(action?{action}:{})}),signal:AbortSignal.timeout(20000)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.message||'Please try again.');const r=result.request;for(const key of ['app','email','device','message'])el(key).textContent=r[key];el('name').textContent=[r.firstName,r.lastName].filter(Boolean).join(' ');el('reference').textContent=r.id;el('availability').textContent=result.availability.message;el('actions').hidden=r.state!=='pending';el('decision-note').hidden=r.state!=='pending';el('request').hidden=false;el('refresh').hidden=false;el('status').className='status';status(r.status);}catch(error){el('status').className='error';status(error.message);el('refresh').hidden=false;}finally{busy=false;for(const b of document.querySelectorAll('button'))b.disabled=false;}}el('approve').addEventListener('click',()=>load('approve'));el('decline').addEventListener('click',()=>load('decline'));el('refresh').addEventListener('click',()=>load());load();})();
</script></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','referrer-policy':'no-referrer','x-robots-tag':'noindex, nofollow','x-frame-options':'DENY','x-content-type-options':'nosniff','content-security-policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'`}});
}
