/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 33ebc3c6b5eb0be44e5e28b07d031941)
interface __BaseEnv_Env {
	TESTFLIGHT_DB: D1Database;
	SUPPORT_EMAIL: SendEmail;
	ATTEMPTS: RateLimit;
	DELIVERIES: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
