/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 505e24881de9d1e8b886badaecf43ade)
interface __BaseEnv_Env {
	SUPPORT_EMAIL: SendEmail;
	ATTEMPTS: RateLimit;
	DELIVERIES: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
